Corrections after rebase.

diff --git a/common/check_config b/common/check_config
--- a/common/check_config
+++ b/common/check_config
@@ -12,24 +12,17 @@ else
     # move into expected repo location
     cd ~/.bash/
 
-	# fetch remotes
-	var=$(git fetch --all 2> /dev/null | tail -n +2)
-	if [ $? -ne 0 ]; then
-	    echo "Could not update configuration repo. Check internet connection?"
-	    return
-	fi
-	# check for updates
-	var=$(git log master..origin/master --oneline)
-	if [ "$var" -ne "" ]; then
-	    echo "Shell configuration is behind. Please update."
-	    return
-	fi
-	# return to previous directory
-	cd - &> /dev/null
+    # fetch remotes
+    var=$(git fetch --all 2> /dev/null | tail -n +2)
+    if [ $? -ne 0 ]; then
+	echo "Could not update configuration repo. Check internet connection?"
+	return
     fi
     # check for updates
     var=$(git log master..origin/master --oneline)
     if [ "${var}" != "" ]; then
 	echo "Shell configuration is behind. Please update."
     fi
+    # return to previous directory
+    cd - &> /dev/null
 fi
